### ISSUE TITLE
Consider choosing an open source license for this code?

### ISSUE THREAD

**Issue by BjarniRunar** [miracle2k/jmap-python#1]
Hello!

I am doing some Python JMAP work, and was considering whether I should build on your work. I like what I see so far!

However, I'd rather not violate your copyright - are you amenable to publishing this under an Open Source license?

Assuming that happens, would you like pull requests if I make changes? I'll be publishing my work on github as well, but won't bother you with issues and PRs unless you want them. I ask because the repo has been idle for some time and you may well have moved on to other things.

Thanks!

**Comment by BjarniRunar** [comment]
Ping!

**Comment by miracle2k** [comment]
Hi, sorry for missing the earlier messages.

Consider it MIT.

Also, I wish I had the time to look at PRs right now, but I don't, so don't waste your time with them.
